version: '3.5'
services:
    frontend:
        image: vue_frontend
        build:
            context: .
            dockerfile: ./.docker/frontend.dockerfile
        networks:
            my-network-name:

    nginx-proxy:
        depends_on:
            - frontend
            - backend
        image: nginx:alpine
        volumes:
            - $PWD/nginx/dev.conf:/etc/nginx/conf.d/default.conf
        networks:
            my-network-name:
                aliases:
                    - proxy-name
        ports:
            - 80:80

    backend:
        restart: always
        image: fastapi_backend
        build:
            context: .
            dockerfile: ./.docker/backend.dockerfile
        env_file: .env
        command:
            - uvicorn app.main:app --reload --host 0.0.0.0 --port 5000
        networks:
            my-network-name:

networks:
    my-network-name:
